### ISSUE TITLE
Error when open http://localhost:3080/

### ISSUE THREAD

**Issue by takaaptech** [siggame/Cerveau#1]
Hi!
First of all, It is really awesome framework! Thanks so much for bring it to us!
I am trying to setup game server. When i start it, it runs fine
Lobby @ 13799 Found game 'Checkers'.
Lobby @ 13799 --- Webserver running on localhost:3080 ---
Lobby @ 13799 --- Lobby listening on localhost:3000 ---
But when open web server, we have bellow error, please help me, i just on the way to learn node js, thank so much!

TypeError: Cannot use 'in' operator to search for 'data' in null
    at Object.compile (/Users/taka/github/Cerveau/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:467:19)
    at HandlebarsEnvironment.hb.compile (/Users/taka/github/Cerveau/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars.js:38:41)
    at ExpressHandlebars._compileTemplate (/Users/taka/github/Cerveau/node_modules/express-handlebars/lib/express-handlebars.js:239:28)
    at ExpressHandlebars.<anonymous> (/Users/taka/github/Cerveau/node_modules/express-handlebars/lib/express-handlebars.js:124:25)
TypeError: Cannot use 'in' operator to search for 'data' in null
    at Object.compile (/Users/taka/github/Cerveau/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:467:19)
    at HandlebarsEnvironment.hb.compile (/Users/taka/github/Cerveau/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars.js:38:41)
    at ExpressHandlebars._compileTemplate (/Users/taka/github/Cerveau/node_modules/express-handlebars/lib/express-handlebars.js:239:28)
    at ExpressHandlebars.<anonymous> (/Users/taka/github/Cerveau/node_modules/express-handlebars/lib/express-handlebars.js:124:25)

**Comment by JacobFischer** [comment]
Verified.

It appears to be a dependency issue. Deleting my local node_modules/ then `npm install` fresh gives the same issue.

I'll try to figure out exactly what is wrong. Probably the wrong version of express in the package.json.

**Comment by takaaptech** [comment]
Ok thank you! It works now.
<img width="899" alt="screen shot 2015-09-29 at 10 47 35 pm" src="https://cloud.githubusercontent.com/assets/6276251/10169634/2f5ed67e-66fc-11e5-8347-3b8086f0ebb9.png">
