### ISSUE TITLE
Server crashes upon recieving an invalid string

### ISSUE THREAD

**Issue by KendallHarter** [siggame/Cerveau#8]
For example, here is the error generated when sending the string "hi\x04" to the server:

```
undefined:1
hi
^

SyntaxError: Unexpected token h
    at Object.parse (native)
    at Object.Class._onSocketData (Cerveau\gameplay\tcpClient.js:30:51)
    at Socket.onSocketData (Cerveau\gameplay\client.js:34:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by KendallHarter** [comment]
This happens upon receiving any invalid JSON.
It can also happen if the JSON is missing expected fields. (e.g., Sending `{"event": "play"}` at the start of the game will also crash the server.)

**Comment by JacobFischer** [comment]
Yeah. I've suspected these things were possible if a client sends unexpected stuff. I'll add more rigorous checking sometime.
